language: cpp
os: linux

jobs:
    include:
        os: linux
        dist: focal
        addons:
            apt:
                update: true
                packages:
                    - g++
                    - cmake
                    - libmysqlcppconn-dev
                    - botan
                    - libbotan-2-dev

script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
