language: cpp
os: linux

jobs:
    include:
        os: linux
        addons:
            apt:
                packages:
                    - g++
                    - cmake
                    - libmysqlcppconn-dev
                    - botan

script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
