language: cpp
os: linux

matrix:
    os: linux
    addons:    
        sudo: false
        compiler: gcc
        apt:
            packages:
                - g++
                - cmake


script:
    - mdkir -p build
    - cd build
    - cmake
    - make