language: cpp
os: linux

matrix:
    include: 
        - os: linux
        addons:    
            compiler: gcc
            apt:
                packages:
                    - g++
                    - cmake


script:
    - mdkir -p build
    - cd build
    - cmake
    - make